### ISSUE TITLE
点击两次的问题

### ISSUE THREAD

**Issue by aiyou666666** [lorecioni/autocomplete.js#2]
选择的时候 需要点击两次 才能选中  需要把change事件 改成 input事件 就可以解决了

**Comment by Quenton2018** [comment]
请问具体一点是改变那个事件

**Comment by lorecioni** [comment]
> 选择的时候 需要点击两次 才能选中 需要把change事件 改成 input事件 就可以解决了

Can you please explain me the issue in english? Thank you!

**Comment by rafachacon** [comment]
@lorecioni, basically, you have to click twice in the hints (li.proposal element) to make it work.

If you open the inspector and write something in the input to get the suggestions and then you select (in the inspector) the ul.proposal-list element, you can do with a click. This made me think about focusing the ul.proposal-list element first. I've tried a workaround applying a focus to the ul.proposal-list with no success.

**Comment by rafachacon** [comment]
By changing
`input.bind("change paste keyup", function(e){`
to
`input.bind("paste keyup", function(e){`
it works fine, as @aiyou666666 suggested.

**Comment by rafachacon** [comment]
@lorecioni, te reason might be:

When clicking in a "hint", the input changes, triggering again the hints list building, creating even more items.

**Comment by lorecioni** [comment]
Bug fix released in v1.0.1, thanks to @aiyou666666 @rafachacon @Quenton2018
